### ISSUE TITLE
The published package is empty

### ISSUE THREAD

**Issue by chocolateboy** [emanuelelongo/fetchetera#3]
There are no JavaScript files in the [published package](https://unpkg.com/browse/fetchetera@1.0.4/), just the README and package.json. This is true of all versions released since [v1.0.0](https://unpkg.com/browse/fetchetera@1.0.0/), which was the last version to include the `dist` directory.

**Comment by chocolateboy** [comment]
P.S. There's no need to include the [tests](https://unpkg.com/browse/fetchetera@1.0.0/dist/__tests__/) in the tarball.

**Comment by emanuelelongo** [comment]
Hey! Really thanks for the contribution! ;)
